# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devkit < Formula
  desc ""
  homepage ""
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/devkit/releases/download/v0.4.0/devkit_0.4.0_darwin_amd64.tar.gz"
      sha256 "a512671a54d9763febd7a832116386fa2fac608796817658ebc8ca650aa217d9"

      def install
        bin.install "devkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/devkit/releases/download/v0.4.0/devkit_0.4.0_darwin_arm64.tar.gz"
      sha256 "07b38b50a6827a83d20e46343a5464b8d9441719aacf49ff3f01337b345caec7"

      def install
        bin.install "devkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/devkit/releases/download/v0.4.0/devkit_0.4.0_linux_amd64.tar.gz"
      sha256 "6d701bb9b2dabe4304db21969ac8adb315ff9801ca41fba6427cfcf99dede9fa"
      def install
        bin.install "devkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/devkit/releases/download/v0.4.0/devkit_0.4.0_linux_arm64.tar.gz"
      sha256 "7036620405112e6d73aac04b8714b80c7ded1c2c308c0bfdb073cd192d932fe8"
      def install
        bin.install "devkit"
      end
    end
  end
end
