# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devkube < Formula
  desc ""
  homepage ""
  version "0.21.2"

  on_macos do
    on_intel do
      url "https://github.com/adrianliechti/devkube/releases/download/v0.21.2/devkube_0.21.2_darwin_amd64.tar.gz"
      sha256 "2a00d6a0a8f7c1ebcef7dfea324e74383130881925d97d4d94314e4c3e2b1af8"

      def install
        bin.install "devkube"
      end
    end
    on_arm do
      url "https://github.com/adrianliechti/devkube/releases/download/v0.21.2/devkube_0.21.2_darwin_arm64.tar.gz"
      sha256 "21834dfaed212695c8415880638b1d1ab45975ec88b51b801700ff9951d218e4"

      def install
        bin.install "devkube"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/devkube/releases/download/v0.21.2/devkube_0.21.2_linux_amd64.tar.gz"
        sha256 "3346c01b99d3f531a02ee4cbb2772dcf1be68be6a9842b619dcb00d2aa276814"

        def install
          bin.install "devkube"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/devkube/releases/download/v0.21.2/devkube_0.21.2_linux_arm64.tar.gz"
        sha256 "4f7405a547d7e496037aeeaa29b98164774e59df80703cf84d1943a3887b54a2"

        def install
          bin.install "devkube"
        end
      end
    end
  end
end
