# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devkit < Formula
  desc ""
  homepage ""
  version "0.2.4"

  on_macos do
    on_intel do
      url "https://github.com/adrianliechti/devkit/releases/download/v0.2.4/devkit_0.2.4_darwin_amd64.tar.gz"
      sha256 "ac0b431da05f92bf30448be4beffb79a400690df3fcf05d4e508b3217b03b18a"

      def install
        bin.install "devkit"
      end
    end
    on_arm do
      url "https://github.com/adrianliechti/devkit/releases/download/v0.2.4/devkit_0.2.4_darwin_arm64.tar.gz"
      sha256 "a313c6cd06e51f365250f14844ad5736d9839baa8853368d986832016f24472f"

      def install
        bin.install "devkit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/devkit/releases/download/v0.2.4/devkit_0.2.4_linux_amd64.tar.gz"
        sha256 "51f9d89cbf814fd99468c31fad5a2bf3de7bf720919dcd1e5fe98d78db0d3902"

        def install
          bin.install "devkit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/devkit/releases/download/v0.2.4/devkit_0.2.4_linux_arm64.tar.gz"
        sha256 "46ced2b2bc659498fa5fde853cfe0e1652352ce315c61e6ae32b103e6ec13bde"

        def install
          bin.install "devkit"
        end
      end
    end
  end
end
