# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devkit < Formula
  desc ""
  homepage ""
  version "0.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/devkit/releases/download/v0.0.8/devkit_0.0.8_darwin_arm64.tar.gz"
      sha256 "8b202244af1145b11a9a196d8cd77fa737681c85e67adf546f46fd6b2a532985"

      def install
        bin.install "devkit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/devkit/releases/download/v0.0.8/devkit_0.0.8_darwin_amd64.tar.gz"
      sha256 "dde713532907e6f46a6f38738b662cb7ff83d2ae3541d7277c7fc23ad37cfb59"

      def install
        bin.install "devkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/devkit/releases/download/v0.0.8/devkit_0.0.8_linux_arm64.tar.gz"
      sha256 "ef89c402cfdf2572eed15c8c5ca532dc7b0698ad9b858a03b0d6d0dc5f38dd25"

      def install
        bin.install "devkit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/devkit/releases/download/v0.0.8/devkit_0.0.8_linux_amd64.tar.gz"
      sha256 "04ab0a45f59c780cb56a95b7d477461a1bb8cb4341c9beb9653c4982238ece1c"

      def install
        bin.install "devkit"
      end
    end
  end
end
