# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devkube < Formula
  desc ""
  homepage ""
  version "0.24.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/devkube/releases/download/v0.24.0/devkube_0.24.0_darwin_amd64.tar.gz"
      sha256 "c5b782879e791ec7c3cdf2c9db1b290e0b7b4578b8d4ac40bb7305e32e0f76dc"

      def install
        bin.install "devkube"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/devkube/releases/download/v0.24.0/devkube_0.24.0_darwin_arm64.tar.gz"
      sha256 "7360f436273769da8ddc18275359c5f39797f06e70d89cc5832be413a6125089"

      def install
        bin.install "devkube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/devkube/releases/download/v0.24.0/devkube_0.24.0_linux_amd64.tar.gz"
        sha256 "a53c3c33481bc98f2be5ec894b827f99636aec97ecfad8bd5698e3729b2ca80e"

        def install
          bin.install "devkube"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/devkube/releases/download/v0.24.0/devkube_0.24.0_linux_arm64.tar.gz"
        sha256 "c863b9901e2f1296713553cf742474a357af8f9a0489b177c1837fb55034a3e3"

        def install
          bin.install "devkube"
        end
      end
    end
  end
end
