# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donkey < Formula
  desc ""
  homepage ""
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/donkey/releases/download/v0.3.2/donkey_darwin_amd64.tar.gz"
      sha256 "5010e8c10a60a06c26c1ffad804873016f969ae66e2e47c5da68ebe120f2359e"

      define_method(:install) do
        bin.install "donkey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/donkey/releases/download/v0.3.2/donkey_darwin_arm64.tar.gz"
      sha256 "e878c29ac50a94b2840e7cf1be998fb40294767547ccdff344c16e07f0bf1821"

      define_method(:install) do
        bin.install "donkey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/donkey/releases/download/v0.3.2/donkey_linux_amd64.tar.gz"
      sha256 "06c2bf1784a50886e837ef1881f151000a0ee671fa75f8465738f75b2f73d4ee"
      define_method(:install) do
        bin.install "donkey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/donkey/releases/download/v0.3.2/donkey_linux_arm64.tar.gz"
      sha256 "0dcd915d6dea8e78af442d42293f2c01775cd18edcf0d05e3bbd03b2e91cacc2"
      define_method(:install) do
        bin.install "donkey"
      end
    end
  end
end
