# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donkey < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/donkey/releases/download/v0.1.0/donkey_darwin_amd64.tar.gz"
      sha256 "1e0ffcab0e096adaacd28b675604efac4ca9267629e85ea7c1a4fda6fc711e1d"

      define_method(:install) do
        bin.install "donkey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/donkey/releases/download/v0.1.0/donkey_darwin_arm64.tar.gz"
      sha256 "17b9e4c97abe58a7e8ae7f5244d646240904997be847a0b65777d47537aa0a17"

      define_method(:install) do
        bin.install "donkey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/donkey/releases/download/v0.1.0/donkey_linux_amd64.tar.gz"
      sha256 "35c1e4bc47970a9f152afe8bdbdeb03ed8e41f6c76921f055b1e4825ee2126f0"
      define_method(:install) do
        bin.install "donkey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/donkey/releases/download/v0.1.0/donkey_linux_arm64.tar.gz"
      sha256 "48579e137eae7df85cca1e882a236482bed1d3ae72a634b0e20fa266817f433d"
      define_method(:install) do
        bin.install "donkey"
      end
    end
  end
end
