# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlDashboard < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/kubectl-dashboard/releases/download/v0.1.1/kubectl-dashboard_0.1.1_darwin_amd64.tar.gz"
      sha256 "8907346a19eb19cb87342410c5df07a2578349e9acd91b2cd2ebd34fb7f2407a"

      def install
        bin.install "kubectl-dashboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/kubectl-dashboard/releases/download/v0.1.1/kubectl-dashboard_0.1.1_darwin_arm64.tar.gz"
      sha256 "bcf39d87b94b31e2e94cd496b78088897ee5f448f5f3c1f3c6f639a7bedef75a"

      def install
        bin.install "kubectl-dashboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/kubectl-dashboard/releases/download/v0.1.1/kubectl-dashboard_0.1.1_linux_amd64.tar.gz"
        sha256 "038588e9b3e26db7be80a8ab297c59f1ac43d4c5451e36d4e2a6fa423cdcaf07"

        def install
          bin.install "kubectl-dashboard"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/kubectl-dashboard/releases/download/v0.1.1/kubectl-dashboard_0.1.1_linux_arm64.tar.gz"
        sha256 "71a4a99cdbd3347cadbd87a97ab5118619fffc9fdded0f88c9c8746b75587967"

        def install
          bin.install "kubectl-dashboard"
        end
      end
    end
  end
end
