# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlDashboard < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/kubectl-dashboard/releases/download/v0.1.0/kubectl-dashboard_0.1.0_darwin_amd64.tar.gz"
      sha256 "1377bbb676d9dad5236ac055b023d95217daf65282956592449666575305f4fa"

      def install
        bin.install "kubectl-dashboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/kubectl-dashboard/releases/download/v0.1.0/kubectl-dashboard_0.1.0_darwin_arm64.tar.gz"
      sha256 "89a492e1287a8c32654c6997904967bec711d95801c2398a8c7031828f20121a"

      def install
        bin.install "kubectl-dashboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/kubectl-dashboard/releases/download/v0.1.0/kubectl-dashboard_0.1.0_linux_amd64.tar.gz"
        sha256 "1a332db7c8794c5da45ccc0d694140462e697df72154a9bf143df9a53667ae2c"

        def install
          bin.install "kubectl-dashboard"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/kubectl-dashboard/releases/download/v0.1.0/kubectl-dashboard_0.1.0_linux_arm64.tar.gz"
        sha256 "f6e93ff9b68deed2a309ac0a9f5e84571ffc1ec848cc572313c87c570cd8f712"

        def install
          bin.install "kubectl-dashboard"
        end
      end
    end
  end
end
