# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlTrail < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/kubectl-trail/releases/download/v0.0.1/kubectl-trail_0.0.1_darwin_amd64.tar.gz"
      sha256 "3ac8de60f443069c0d53c02db580a3b8ddd284c2fd7a53ab67db0af0e825c2e0"

      def install
        bin.install "kubectl-trail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/kubectl-trail/releases/download/v0.0.1/kubectl-trail_0.0.1_darwin_arm64.tar.gz"
      sha256 "37b320c20620514fcd35644bbfe4bff564da10a495bd582772e445cb1ec335cb"

      def install
        bin.install "kubectl-trail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/kubectl-trail/releases/download/v0.0.1/kubectl-trail_0.0.1_linux_amd64.tar.gz"
        sha256 "1ff777a905cf55945e9521e7ad5fec95ff9e79d8a4a55a4d0d4881fe91273981"

        def install
          bin.install "kubectl-trail"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/kubectl-trail/releases/download/v0.0.1/kubectl-trail_0.0.1_linux_arm64.tar.gz"
        sha256 "62c36988f89f675b660fe86e9b2ae9a454b57837b6e139c6cdcc347bbd144656"

        def install
          bin.install "kubectl-trail"
        end
      end
    end
  end
end
