# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loop < Formula
  desc ""
  homepage ""
  version "0.30.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/loop/releases/download/v0.30.3/loop_0.30.3_darwin_amd64.tar.gz"
      sha256 "6cbe67ca1fd27ae20c1f5ecc5c5a23445c4f97f481e8d5b26b89ac906cecbc9f"

      define_method(:install) do
        bin.install "loop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/loop/releases/download/v0.30.3/loop_0.30.3_darwin_arm64.tar.gz"
      sha256 "312690574be99008f38973fcd88c304f61dc73142f387146c061c70124c75976"

      define_method(:install) do
        bin.install "loop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/loop/releases/download/v0.30.3/loop_0.30.3_linux_amd64.tar.gz"
      sha256 "aecf52ce262f8378f7f8a6e2c3f5435fe92cb5cf346dbc4d0b97e4b7c13d47ae"
      define_method(:install) do
        bin.install "loop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/loop/releases/download/v0.30.3/loop_0.30.3_linux_arm64.tar.gz"
      sha256 "35b30d7f5afdaec14ab5b2c3891c623ac6af7c87277425e99d4012d642762f4a"
      define_method(:install) do
        bin.install "loop"
      end
    end
  end
end
