# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loop < Formula
  desc ""
  homepage ""
  version "0.20.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/loop/releases/download/v0.20.0/loop_0.20.0_darwin_amd64.tar.gz"
      sha256 "c2cf80390be5e87d2cfc52d17d22e44e5881256f94d6b1ce5a3572f157dd22e4"

      def install
        bin.install "loop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/loop/releases/download/v0.20.0/loop_0.20.0_darwin_arm64.tar.gz"
      sha256 "5142139586aafdd624aab60a7cec283047bd1cceb66dbc959ad57d0c5657a4b3"

      def install
        bin.install "loop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/loop/releases/download/v0.20.0/loop_0.20.0_linux_amd64.tar.gz"
      sha256 "26b8c86d7c6f6ffedebbefffe0ed4fd309e80c86ae8d304bdb9cc85fb85be5df"
      def install
        bin.install "loop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/loop/releases/download/v0.20.0/loop_0.20.0_linux_arm64.tar.gz"
      sha256 "7dbae9837aa846bf44f0ed29eccf4b374d6ff2f8fdbcc3f3ed0728a7a880f68d"
      def install
        bin.install "loop"
      end
    end
  end
end
