# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tunnel < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/tunnel/releases/download/v0.0.2/tunnel_0.0.2_darwin_amd64.tar.gz"
      sha256 "5ce3b003afbb2b42227defc04c47bbfa682994b8876b49e205d045025b292774"

      def install
        bin.install "tunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/tunnel/releases/download/v0.0.2/tunnel_0.0.2_darwin_arm64.tar.gz"
      sha256 "d56f8085aab04e33a9e3bc8cc4409c257fdd1e4cb135b605fed8e8e5f09c5293"

      def install
        bin.install "tunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/tunnel/releases/download/v0.0.2/tunnel_0.0.2_linux_amd64.tar.gz"
      sha256 "8db880016221dcffd9b2ff647b28d46920c41a9a294c4f83ce0d4d099f5d488c"
      def install
        bin.install "tunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/tunnel/releases/download/v0.0.2/tunnel_0.0.2_linux_arm64.tar.gz"
      sha256 "e1ddbca9e80e20e1e6d3cbb9046aafd2974db27467eefdcec466905120864e2b"
      def install
        bin.install "tunnel"
      end
    end
  end
end
