# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tunnel < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/tunnel/releases/download/v0.0.1/tunnel_0.0.1_darwin_amd64.tar.gz"
      sha256 "a60e90175acc2f645ea7364957cf77ca09068446ca1749a541b861be7fc9a1cf"

      def install
        bin.install "tunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/tunnel/releases/download/v0.0.1/tunnel_0.0.1_darwin_arm64.tar.gz"
      sha256 "2fe8f9cfaaa4d7a76fd23aa450c0ad21278a748709ff36926fcb240a49248591"

      def install
        bin.install "tunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/tunnel/releases/download/v0.0.1/tunnel_0.0.1_linux_amd64.tar.gz"
        sha256 "a0c3a4d2ea0d5b39accb503d1701504dd4796d6ef74be3a9bc7f809d8bc165b3"

        def install
          bin.install "tunnel"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/tunnel/releases/download/v0.0.1/tunnel_0.0.1_linux_arm64.tar.gz"
        sha256 "669004aa19a857bf2a4042e2fffb1a04f28e5eba15099958807b719b537a879b"

        def install
          bin.install "tunnel"
        end
      end
    end
  end
end
