# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wingman < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/wingman/releases/download/v0.0.1/wingman_0.0.1_darwin_amd64.tar.gz"
      sha256 "0f5f94fdf3ca508f2fd9419e23c38e1d3a47642258d92b4c9bc0a7f7e339abc4"

      def install
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/wingman/releases/download/v0.0.1/wingman_0.0.1_darwin_arm64.tar.gz"
      sha256 "b0f50fa712f8d6dcfdd337c40cf58ed786a1b2695a21d64e84860c4e1f8735d8"

      def install
        bin.install "wingman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/wingman/releases/download/v0.0.1/wingman_0.0.1_linux_amd64.tar.gz"
        sha256 "72ded74aac9a470940273e2191099f80609222eef5a9e16defac218eb95a5a29"

        def install
          bin.install "wingman"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/wingman/releases/download/v0.0.1/wingman_0.0.1_linux_arm64.tar.gz"
        sha256 "0f329b0282cd3c8cd760f685b297a73adf68b1dbd8d1ef70e4115d45754abd57"

        def install
          bin.install "wingman"
        end
      end
    end
  end
end
