# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WingmanAgent < Formula
  desc ""
  homepage ""
  version "0.6.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.7/wingman-agent_0.6.7_darwin_amd64.tar.gz"
      sha256 "0c60c123892ac83852d0929df4dc89ba53c87fbfdb01adcded42645331aa6ff4"

      define_method(:install) do
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.7/wingman-agent_0.6.7_darwin_arm64.tar.gz"
      sha256 "0493ad184d3a53e41c7f943dc0460c092c45b45657f5e15359df4f780a145ae7"

      define_method(:install) do
        bin.install "wingman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.7/wingman-agent_0.6.7_linux_amd64.tar.gz"
      sha256 "92e5b2cdff41aa37a00f82c353bfcc20c18e9712dc0cb583947d3ffba2b24166"
      define_method(:install) do
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.7/wingman-agent_0.6.7_linux_arm64.tar.gz"
      sha256 "9293286fe46ec2140f28336240dd729d63f60f8573b495ec92158e0f8bd3f1e3"
      define_method(:install) do
        bin.install "wingman"
      end
    end
  end
end
