# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wingman < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/wingman/releases/download/v0.0.3/wingman_0.0.3_darwin_amd64.tar.gz"
      sha256 "645df20614ba24d8d43ee58298e16858051c9b03d66e2156630e4c617cbfce1c"

      def install
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/wingman/releases/download/v0.0.3/wingman_0.0.3_darwin_arm64.tar.gz"
      sha256 "3c7444dc55ca0e6d580cd251fd8ede84a17c05531344747e48bcf5fa368f8748"

      def install
        bin.install "wingman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/wingman/releases/download/v0.0.3/wingman_0.0.3_linux_amd64.tar.gz"
        sha256 "9d58c86428c7373af3296c6bd47988e9d0350bded36c464aa6b9890e6d34ffb3"

        def install
          bin.install "wingman"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/wingman/releases/download/v0.0.3/wingman_0.0.3_linux_arm64.tar.gz"
        sha256 "32b220f7d85e6b0c971114711e94f9c5de8870d9f5b697f3e9829da2e71e038c"

        def install
          bin.install "wingman"
        end
      end
    end
  end
end
