# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WingmanCli < Formula
  desc ""
  homepage ""
  version "0.0.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.0.13/wingman-cli_0.0.13_darwin_amd64.tar.gz"
      sha256 "e615371689fb29f250bee6f4e7ca1f753caa5d1aa49297121ab97d35acc14d9b"

      def install
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.0.13/wingman-cli_0.0.13_darwin_arm64.tar.gz"
      sha256 "39ef34984852302c071e2879e42d0aa1d3d09744e969887f4c90faedb9134607"

      def install
        bin.install "wingman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.0.13/wingman-cli_0.0.13_linux_amd64.tar.gz"
        sha256 "ff977720b4cb769b1d454a8fa6c505fcb303664571919576b121890c49b54dd3"

        def install
          bin.install "wingman"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.0.13/wingman-cli_0.0.13_linux_arm64.tar.gz"
        sha256 "d95942205a284f86fc50c20c76649fc71d327d4795b724e2a9ded52d4131836d"

        def install
          bin.install "wingman"
        end
      end
    end
  end
end
