# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WingmanCli < Formula
  desc ""
  homepage ""
  version "0.0.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.0.12/wingman-cli_0.0.12_darwin_amd64.tar.gz"
      sha256 "983a12098e12411748e0105c54931390e3b10b210dc7fc060b5fbf372381db2a"

      def install
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.0.12/wingman-cli_0.0.12_darwin_arm64.tar.gz"
      sha256 "47592784f68b1ad4c0e4a4d3105fc6e7b553e7fe1fae458d38a5adb89dc3da37"

      def install
        bin.install "wingman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.0.12/wingman-cli_0.0.12_linux_amd64.tar.gz"
        sha256 "e334f5dbaa046a7d3f6993a1f390dca088a2ec92b85c07350dcf6e483a150ae8"

        def install
          bin.install "wingman"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.0.12/wingman-cli_0.0.12_linux_arm64.tar.gz"
        sha256 "26e703afd54ece798613cd7460feca4f00dc4956729057414ba905f4f3620d6e"

        def install
          bin.install "wingman"
        end
      end
    end
  end
end
