# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WingmanAgent < Formula
  desc ""
  homepage ""
  version "0.6.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.9/wingman-agent_0.6.9_darwin_amd64.tar.gz"
      sha256 "25018267c82810457d99792192aaad11e9590dfe1cb300584bb12d7167a3e141"

      define_method(:install) do
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.9/wingman-agent_0.6.9_darwin_arm64.tar.gz"
      sha256 "ed8f5be8d39ab426f8d900becc5cb8e3276edc3aef6384d40be7852cf6a201b6"

      define_method(:install) do
        bin.install "wingman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.9/wingman-agent_0.6.9_linux_amd64.tar.gz"
      sha256 "d5e59f2f40332a6b0a89693d4d5d9bfcc2012a6200a15ecbb8c3a201bab3d018"
      define_method(:install) do
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.9/wingman-agent_0.6.9_linux_arm64.tar.gz"
      sha256 "77023a0ca26f36c608f4887e037327cd955c2e66483d07a0f2eb4ef10a8c820a"
      define_method(:install) do
        bin.install "wingman"
      end
    end
  end
end
