# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WingmanCli < Formula
  desc ""
  homepage ""
  version "0.3.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.3.11/wingman-cli_0.3.11_darwin_amd64.tar.gz"
      sha256 "d64d8e486a9629484139196e01d3bedd9c9af1d519abf4a48dd5a9f46b4df2c0"

      def install
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.3.11/wingman-cli_0.3.11_darwin_arm64.tar.gz"
      sha256 "3db8f6b7594c2ec726804ed53642b028b6a956c1e2c59aa85c38865227f3f503"

      def install
        bin.install "wingman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.3.11/wingman-cli_0.3.11_linux_amd64.tar.gz"
      sha256 "576d080a79f40fe27548dd298b3bfb35259612771c8e4b0f971f7fdf11d088a3"
      def install
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/wingman-cli/releases/download/v0.3.11/wingman-cli_0.3.11_linux_arm64.tar.gz"
      sha256 "e55dfbc7304fff54df3e67bfd6dea5bc57a644be02f108da3284402d2c88053b"
      def install
        bin.install "wingman"
      end
    end
  end
end
