# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WingmanAgent < Formula
  desc ""
  homepage ""
  version "0.6.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.2/wingman-agent_0.6.2_darwin_amd64.tar.gz"
      sha256 "3d1be91d7dff3e91d82192dd67f31030b718184edd4364b4c2522e02eb17a5dd"

      define_method(:install) do
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.2/wingman-agent_0.6.2_darwin_arm64.tar.gz"
      sha256 "90fa0cc3b8b648b72db07f88e2442c87659941391dd9e8d7f2b3084903b8809d"

      define_method(:install) do
        bin.install "wingman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.2/wingman-agent_0.6.2_linux_amd64.tar.gz"
      sha256 "3a2b8346b40702a547d9690dab6d7a644f5a6ad06a970a47a341af64f9b14d20"
      define_method(:install) do
        bin.install "wingman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v0.6.2/wingman-agent_0.6.2_linux_arm64.tar.gz"
      sha256 "59e4c0d74028f8752de289f859a60b74a1574ee0cc36bd6dbb7b499270476e45"
      define_method(:install) do
        bin.install "wingman"
      end
    end
  end
end
