# This file was generated by GoReleaser. DO NOT EDIT.
cask "donkey" do
  version "0.6.3"

  on_macos do
    on_arm do
      sha256 "06c8f65cbbe472729933e8d67a7e284c9b2dc00610afd1cc41f74e5c0ecef615"
      url "https://github.com/adrianliechti/donkey/releases/download/v#{version}/donkey_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "91e606454bb2902984a9943b1b26349e5cb13405c05ebc8007531687873f51a5"
      url "https://github.com/adrianliechti/donkey/releases/download/v#{version}/donkey_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fd33c034479c40cdf7c5e7f94c3e855d4656028ce2e63714bee28de46cbe8381"
      url "https://github.com/adrianliechti/donkey/releases/download/v#{version}/donkey_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "49e32e1f1babc78515d554c21289dc846803c88e30c8881a288b66da110e311b"
      url "https://github.com/adrianliechti/donkey/releases/download/v#{version}/donkey_linux_amd64.tar.gz"
    end
  end

  name "donkey"
  desc "Deploy applications to Kubernetes"
  homepage "https://github.com/adrianliechti/donkey"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "donkey"

  # No zap stanza required

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/donkey"]
    end
  end
end
