# This file was generated by GoReleaser. DO NOT EDIT.
cask "donkey" do
  version "0.6.2"

  on_macos do
    on_arm do
      sha256 "60e66e16ff465063b4c4fdbab16d6c3689586cb75b6c5c1d40b3e44a78deb45e"
      url "https://github.com/adrianliechti/donkey/releases/download/v#{version}/donkey_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2702420208a2208f79fde0fdc684488345aff5c7c97df1185a072dd4c53a19ef"
      url "https://github.com/adrianliechti/donkey/releases/download/v#{version}/donkey_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c7e5721bd8d4464ff7784774556cefd88e0769e5f689282eb0a394fc51896a97"
      url "https://github.com/adrianliechti/donkey/releases/download/v#{version}/donkey_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "57949f666428e212bf2e9aab355d91e76d1a1f32faaa4f106e97acdff38c0085"
      url "https://github.com/adrianliechti/donkey/releases/download/v#{version}/donkey_linux_amd64.tar.gz"
    end
  end

  name "donkey"
  desc "Deploy applications to Kubernetes"
  homepage "https://github.com/adrianliechti/donkey"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "donkey"

  # No zap stanza required

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/donkey"]
    end
  end
end
