# This file was generated by GoReleaser. DO NOT EDIT.
cask "prism-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "85e8f1e5ae9f39124b67f78c495ff0164eb777df885b9bfebad969a7408e9ff2"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6236e005de2d8d8046624b4baa23720e23cae481e6e9bab24187a454890bcb9"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f72378621f060b400bc4dcf58d5374de3c0b58e296ad3417c00a11283bf196a8"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f816045ec84a5c1dd79fd726014914db729121e147c26de6ca1b2c9f4ff22824"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prism-cli"
  desc "Insomnia/Postman-like API client, running locally in your browser"
  homepage "https://github.com/adrianliechti/prism"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prism"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prism"]
    end
  end

  # No zap stanza required

end
