# This file was generated by GoReleaser. DO NOT EDIT.
cask "prism-cli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "b4b1969d86ea5d41bb315bb86c7ddb72d0e972f93dddb0bc04177886577ffec9"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "52d399cd93cfdf78486657b88207994fba1664d38217e38e437e91a130cc3381"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a07418631a4ce5f1069454f6b42e505916395887a7ef60ff0e9025b9e594d7be"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "355ab3060edc98fd757ef67250668fd14c735bfee3f358b6c256c4e1427c6c42"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prism-cli"
  desc "Insomnia/Postman-like API client, running locally in your browser"
  homepage "https://github.com/adrianliechti/prism"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prism"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prism"]
    end
  end

  # No zap stanza required

end
