# This file was generated by GoReleaser. DO NOT EDIT.
cask "prism-cli" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "b2d11d971608662c91059e2529a6229d364159f9a742fe9350ab2ea4be931f6c"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6bde2fb2dd3ff7e9c81b4b0d6f8d8f88ef297b71f36b30da75e63a25574188f2"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3fdcb05369ba954e4a0db074116162795af5cfa2b9e76b5d3fe083391f2988b6"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a2607c8de896000e033e5930206462bd4b49c9b2d17597a27514fed2b86a8f9"
      url "https://github.com/adrianliechti/prism/releases/download/v#{version}/prism_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prism-cli"
  desc "Insomnia/Postman-like API client, running locally in your browser"
  homepage "https://github.com/adrianliechti/prism"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prism"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prism"]
    end
  end

  # No zap stanza required

end
