# This file was generated by GoReleaser. DO NOT EDIT.
cask "wingman-agent" do
  version "0.5.3"

  on_macos do
    on_intel do
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_amd64.tar.gz"
      sha256 "05dd01363d5c7ec03870d0da94c3da1d2520d2eb1ed497c9df3bce9760a24e40"
    end
    on_arm do
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_arm64.tar.gz"
      sha256 "14a757e3aa580f76ae377cd0add4de7793558706753ec55a8a80617e6d73a24b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_amd64.tar.gz"
      sha256 "49d670fc6035011470bf4ae26556cb5adfd00c29c665dabb47cd3850d4b21b7f"
    end
    on_arm do
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_arm64.tar.gz"
      sha256 "3bead30b2a6397e7f7c4aafb4e16a492ec0e37f6f84b2c62cf9069469cff3234"
    end
  end

  name "wingman-agent"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wingman"

  # No zap stanza required

end
