# This file was generated by GoReleaser. DO NOT EDIT.
cask "wingman" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "8841122438f246da80204d018e6b4a9455c1fee3f4dfacfa8c343b071f3e5da6"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "72ce93dd52a0eb2f39fdf16abd856dcebc2a438f5c124d91683ce5a6b9e5cd24"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a357249c6763644bbdeac7d1d77e199ebb3fc80534ee6b791eba3c1f35998dd"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e628350b6cc326d2383c3f7d63eb7c84b2901182b4a487958fac215a76c06b83"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wingman"
  desc "AI-powered coding assistant for your terminal"
  homepage "https://github.com/adrianliechti/wingman-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wingman"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wingman"]
    end
  end

  # No zap stanza required

end
