# This file was generated by GoReleaser. DO NOT EDIT.
cask "wingman-cli" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "6a3f29cadc203af8b2a6bbec33cf946c81d23a916f5c0854684b33bc5e4fa89d"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0a92e51be5cbc13d21088390dd635582687f8781f503f7245ec79637018b5c78"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "43e13504e55b92efeecc82052d8c55895549e7c194e06e4c3125b322d2b287c2"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "963c098531732d1770827eb996a45dff8aee15a4324b9ecae2382233834aa842"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wingman-cli"
  desc "AI-powered coding assistant for your terminal"
  homepage "https://github.com/adrianliechti/wingman-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wingman"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wingman"]
    end
  end

  # No zap stanza required

end
