# This file was generated by GoReleaser. DO NOT EDIT.
cask "wingman-cli" do
  version "0.15.4"

  on_macos do
    on_arm do
      sha256 "150787f6748f4afb1033622f131e9ebf38e34d6cc63c34455b541d6d8d5614be"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0d6ba6561fbaf50732ff01eb696af1befefc9ffe225070312ee08f8ab8c7c24c"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "245b443e39e086eedb4aa242ceec713e5be68e79f050af6fd6b626ec365b0a34"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b013dd18411fe6d89029ba22f6dd9b925627b7e38fee23432cdf0039901b0bbc"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wingman-cli"
  desc "AI-powered coding assistant for your terminal"
  homepage "https://github.com/adrianliechti/wingman-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wingman"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wingman"]
    end
  end

  # No zap stanza required
end
