# This file was generated by GoReleaser. DO NOT EDIT.
cask "wingman-cli" do
  version "0.11.9"

  on_macos do
    on_intel do
      sha256 "17c743b81768112dfdf7b48f415aa3b51ce0d578eec488a6f6ba7585235b617a"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d10c5956d08ce7ac462ad0153f229dae18ccfb0a196481bf249ad10bc61aebc"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "20dd58fc79c21edfe354157ac4a077181f767c8f0ec718e2e1334c31dca42c22"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "27307c7d84b54ea741fcf977d9c11ca676b86416173dbcf98d4fc775a0321f9c"
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wingman-cli"
  desc "AI-powered coding assistant for your terminal"
  homepage "https://github.com/adrianliechti/wingman-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wingman"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wingman"]
    end
  end

  # No zap stanza required

end
