# This file was generated by GoReleaser. DO NOT EDIT.
cask "wingman-agent" do
  version "0.5.2"

  on_macos do
    on_intel do
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_amd64.tar.gz"
      sha256 "1fbc1c1359c09db1572fba96f057c4456688c50528fc5036158c610e8ad84965"
    end
    on_arm do
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_darwin_arm64.tar.gz"
      sha256 "81844bf997b8a4d4d5e2c8142a712902bf6668a9422733cc1b5c940438bb1ab8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_amd64.tar.gz"
      sha256 "15de6afa8dfb2d14c790070f12489cf2d67e2815bdac6e4173662499578286cf"
    end
    on_arm do
      url "https://github.com/adrianliechti/wingman-agent/releases/download/v#{version}/wingman-agent_#{version}_linux_arm64.tar.gz"
      sha256 "19ecaa02443f7360da8f36f68c3808fc9a879fc20f7381d6fb7c705f8ae67808"
    end
  end

  name "wingman-agent"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wingman-agent"

  # No zap stanza required

end
